### ISSUE TITLE
成员可选的情况，如何处理

### ISSUE THREAD

**Issue by lslp-github** [hyt100/json_transfer#1]
如果某个成员可带可不带的情况怎么处理
eg
{
    "name":"github",
    "age":10,
}
age有时候会携带，有时候不会携带

**Comment by hyt100** [comment]
目前未实现成员可选，给出的数据结构必须全部搜索到，解析才返回成功。
要支持成员可选，可以在type上增加OPTION标识，扫描数据结构的时候没搜索到则忽略。
